"""PDF report generation for portfolios."""
import io
import os
from datetime import date
from typing import Literal

from fastapi import APIRouter, Depends, Query
from fastapi.responses import StreamingResponse

from app.api.deps import get_current_user, get_portfolio_or_403
from app.services.portfolio_service import portfolio_service

router = APIRouter(tags=["reports"])

Lang = Literal["ru", "en"]

# ── Localisation strings ──────────────────────────────────────────────────────

_I18N: dict[str, dict[str, str]] = {
    "ru": {
        "title":           "Отчёт по портфелю облигаций",
        "portfolio":       "Портфель",
        "generated":       "Дата формирования",
        "summary":         "Сводка",
        "metric":          "Показатель",
        "value":           "Значение",
        "total_value":     "Текущая стоимость",
        "total_cost":      "Стоимость покупки",
        "pnl":             "Прибыль / убыток",
        "pnl_pct":         "P&L, %",
        "annual_coupon":   "Годовой купонный доход",
        "avg_ytm":         "Средний YTM портфеля",
        "count":           "Кол-во инструментов",
        "bonds_count":     "Из них облигаций",
        "instruments":     "Состав портфеля",
        "col_n":           "№",
        "col_ticker":      "Тикер",
        "col_name":        "Название",
        "col_type":        "Тип",
        "col_qty":         "Кол-во",
        "col_buy":         "Цена покупки",
        "col_cur":         "Тек. цена",
        "col_value":       "Стоимость",
        "col_pnl":         "P&L",
        "col_pnl_pct":     "P&L%",
        "col_rating":      "Рейтинг",
        "col_coupon":      "Купон/год, ₽",
        "col_coupon_rate": "Ставка купона",
        "col_ytm":         "YTM",
        "col_maturity":    "Погашение",
        "col_next_coupon": "След. купон",
        "col_weight":      "Доля",
        "type_bond":       "Облигация",
        "type_stock":      "Акция",
        "total_row":       "ИТОГО",
        "footer":          "Сформировано системой Bond AI · Данные предоставлены Московской биржей",
        "rub":             "₽",
        "na":              "—",
        "top_holdings":    "Топ-5 позиций по стоимости",
        "col_share":       "Доля",
        "disclaimer":      "Отчёт носит информационный характер и не является инвестиционной рекомендацией.",
    },
    "en": {
        "title":           "Bond Portfolio Report",
        "portfolio":       "Portfolio",
        "generated":       "Generated",
        "summary":         "Summary",
        "metric":          "Metric",
        "value":           "Value",
        "total_value":     "Current value",
        "total_cost":      "Purchase cost",
        "pnl":             "Profit / Loss",
        "pnl_pct":         "P&L, %",
        "annual_coupon":   "Annual coupon income",
        "avg_ytm":         "Portfolio avg YTM",
        "count":           "Instruments",
        "bonds_count":     "Bonds",
        "instruments":     "Portfolio holdings",
        "col_n":           "#",
        "col_ticker":      "Ticker",
        "col_name":        "Name",
        "col_type":        "Type",
        "col_qty":         "Qty",
        "col_buy":         "Buy price",
        "col_cur":         "Cur. price",
        "col_value":       "Value",
        "col_pnl":         "P&L",
        "col_pnl_pct":     "P&L%",
        "col_rating":      "Rating",
        "col_coupon":      "Coupon/yr",
        "col_coupon_rate": "Coupon rate",
        "col_ytm":         "YTM",
        "col_maturity":    "Maturity",
        "col_next_coupon": "Next coupon",
        "col_weight":      "Weight",
        "type_bond":       "Bond",
        "type_stock":      "Stock",
        "total_row":       "TOTAL",
        "footer":          "Generated by Bond AI · Data provided by Moscow Exchange (MOEX)",
        "rub":             "RUB",
        "na":              "—",
        "top_holdings":    "Top-5 holdings by value",
        "col_share":       "Share",
        "disclaimer":      "This report is for informational purposes only and does not constitute investment advice.",
    },
}


def _t(lang: str, key: str) -> str:
    return _I18N.get(lang, _I18N["ru"]).get(key, key)


# ── Route ─────────────────────────────────────────────────────────────────────

@router.get("/portfolios/{portfolio_id}/report.pdf")
async def export_portfolio_pdf(
    portfolio_id: int,
    lang: Lang = Query("ru"),
    current_user: dict = Depends(get_current_user),
) -> StreamingResponse:
    """Export portfolio as PDF report."""
    portfolio = await get_portfolio_or_403(portfolio_id, current_user)
    rows = await portfolio_service.get_table(portfolio_id)

    pdf_bytes = _generate_pdf(portfolio["name"], rows, lang)

    today = date.today().isoformat()
    filename = f"portfolio_{portfolio_id}_{today}.pdf"
    return StreamingResponse(
        io.BytesIO(pdf_bytes),
        media_type="application/pdf",
        headers={"Content-Disposition": f"attachment; filename={filename}"},
    )


# ── PDF generation ────────────────────────────────────────────────────────────

def _generate_pdf(portfolio_name: str, rows, lang: str = "ru") -> bytes:
    try:
        return _generate_pdf_reportlab(portfolio_name, rows, lang)
    except ImportError:
        return _generate_pdf_fpdf(portfolio_name, rows, lang)


def _find_cyrillic_font() -> tuple[str, str | None]:
    """Return (registered_name, path_or_None). Falls back to Helvetica."""
    candidates = [
        "/usr/share/fonts/truetype/dejavu/DejaVuSans.ttf",
        "/usr/share/fonts/dejavu/DejaVuSans.ttf",
        "/usr/share/fonts/truetype/freefont/FreeSans.ttf",
        "/usr/share/fonts/truetype/liberation/LiberationSans-Regular.ttf",
        "/usr/share/fonts/truetype/ubuntu/Ubuntu-R.ttf",
    ]
    for p in candidates:
        if os.path.exists(p):
            return "CyrillicFont", p
    return "Helvetica", None


def _find_cyrillic_font_bold() -> tuple[str, str | None]:
    candidates = [
        "/usr/share/fonts/truetype/dejavu/DejaVuSans-Bold.ttf",
        "/usr/share/fonts/dejavu/DejaVuSans-Bold.ttf",
        "/usr/share/fonts/truetype/freefont/FreeSansBold.ttf",
        "/usr/share/fonts/truetype/liberation/LiberationSans-Bold.ttf",
        "/usr/share/fonts/truetype/ubuntu/Ubuntu-B.ttf",
    ]
    for p in candidates:
        if os.path.exists(p):
            return "CyrillicFontBold", p
    return "Helvetica-Bold", None


def _generate_pdf_reportlab(portfolio_name: str, rows, lang: str) -> bytes:
    from reportlab.lib import colors
    from reportlab.lib.enums import TA_CENTER, TA_LEFT
    from reportlab.lib.pagesizes import A4, landscape
    from reportlab.lib.styles import ParagraphStyle
    from reportlab.lib.units import cm
    from reportlab.platypus import (
        SimpleDocTemplate, Table, TableStyle, Paragraph, Spacer, HRFlowable,
    )
    from reportlab.pdfbase import pdfmetrics
    from reportlab.pdfbase.ttfonts import TTFont

    t = lambda key: _t(lang, key)

    # ── Fonts ──────────────────────────────────────────────────────────────
    font_name, font_path = _find_cyrillic_font()
    font_bold, bold_path = _find_cyrillic_font_bold()

    if font_path:
        try:
            pdfmetrics.registerFont(TTFont(font_name, font_path))
        except Exception:
            font_name = "Helvetica"
    if bold_path:
        try:
            pdfmetrics.registerFont(TTFont(font_bold, bold_path))
        except Exception:
            font_bold = "Helvetica-Bold"

    # ── Styles ─────────────────────────────────────────────────────────────
    C_DARK   = colors.HexColor("#0f172a")
    C_BLUE   = colors.HexColor("#1e40af")
    C_BLUE2  = colors.HexColor("#2563eb")
    C_LIGHT  = colors.HexColor("#f8fafc")
    C_STRIPE = colors.HexColor("#f1f5f9")
    C_BORDER = colors.HexColor("#e2e8f0")
    C_GREEN  = colors.HexColor("#16a34a")
    C_RED    = colors.HexColor("#dc2626")
    C_GREY   = colors.HexColor("#64748b")
    C_MUTED  = colors.HexColor("#94a3b8")

    title_style = ParagraphStyle("title",   fontName=font_bold, fontSize=18, spaceAfter=2, textColor=C_DARK)
    sub_style   = ParagraphStyle("sub",     fontName=font_name, fontSize=10, spaceAfter=2, textColor=C_GREY)
    head_style  = ParagraphStyle("head",    fontName=font_bold, fontSize=12, spaceBefore=10, spaceAfter=4, textColor=C_DARK)
    disc_style  = ParagraphStyle("disc",    fontName=font_name, fontSize=7,  spaceAfter=2, textColor=C_MUTED)
    foot_style  = ParagraphStyle("footer",  fontName=font_name, fontSize=7,  textColor=C_MUTED)
    # Styles for table cells — enables word wrap for long names
    cell_style        = ParagraphStyle("cell",       fontName=font_name, fontSize=7,   leading=8.5,  textColor=C_DARK)
    cell_style_r      = ParagraphStyle("cell_r",     fontName=font_name, fontSize=7,   leading=8.5,  textColor=C_DARK, alignment=2)  # RIGHT
    header_cell_style = ParagraphStyle("header_cell",fontName=font_bold, fontSize=7.5, leading=9,    textColor=colors.white, alignment=TA_CENTER)

    # ── Document ───────────────────────────────────────────────────────────
    buf = io.BytesIO()

    # Use page template with footer
    from reportlab.platypus import BaseDocTemplate, Frame, PageTemplate
    from reportlab.lib.units import cm as _cm

    PAGE = landscape(A4)
    W, H = PAGE
    MARGIN = 0.8 * cm

    def _footer(canvas, doc):
        canvas.saveState()
        canvas.setFont(font_name, 7)
        canvas.setFillColor(C_MUTED)
        canvas.drawString(MARGIN, 0.8 * cm, t("footer"))
        canvas.drawRightString(W - MARGIN, 0.8 * cm, f"{date.today().isoformat()}  |  {doc.page}")
        canvas.restoreState()

    frame = Frame(MARGIN, 1.5 * cm, W - 2 * MARGIN, H - 2.5 * cm, id="main")
    template = PageTemplate(id="main", frames=[frame], onPage=_footer)
    doc = BaseDocTemplate(
        buf,
        pagesize=PAGE,
        leftMargin=MARGIN, rightMargin=MARGIN,
        topMargin=MARGIN, bottomMargin=1.8 * cm,
        pageTemplates=[template],
    )

    elements = []

    # ── Header block ───────────────────────────────────────────────────────
    today_str = date.today().strftime("%d.%m.%Y") if lang == "ru" else date.today().isoformat()

    elements.append(Paragraph(t("title"), title_style))
    elements.append(Paragraph(f"{t('portfolio')}: <b>{portfolio_name}</b>", sub_style))
    elements.append(Paragraph(f"{t('generated')}: {today_str}", sub_style))
    elements.append(HRFlowable(width="100%", thickness=1, color=C_BORDER, spaceAfter=6))

    # ── Metrics calculation ────────────────────────────────────────────────
    bonds = [r for r in rows if getattr(r, "type", "") == "bond"]
    total_value  = sum(r.current_value or 0 for r in rows)
    total_cost   = sum((r.purchase_price or 0) * (r.quantity or 0) for r in rows)
    total_profit = total_value - total_cost
    pnl_pct = (total_profit / total_cost * 100) if total_cost else 0

    def _coupon_freq(period: int | None) -> int:
        if not period or period <= 0: return 2
        if period <= 35:  return 12
        if period <= 100: return 4
        if period <= 200: return 2
        return 1

    annual_coupon = sum(
        (r.coupon or 0) * (r.quantity or 0) * _coupon_freq(r.coupon_period)
        for r in bonds
    )

    ytm_bonds = [r for r in bonds if getattr(r, "market_yield", None)]
    avg_ytm = (sum(r.market_yield for r in ytm_bonds) / len(ytm_bonds)) if ytm_bonds else None

    rub = t("rub")
    pnl_sign = "+" if total_profit >= 0 else ""
    pnl_sign_pct = "+" if pnl_pct >= 0 else ""

    def _fmt(v: float) -> str:
        return f"{v:,.0f}".replace(",", " ")

    def _fmt2(v: float) -> str:
        return f"{v:,.2f}".replace(",", " ")

    # ── Summary table ─────────────────────────────────────────────────────
    elements.append(Paragraph(t("summary"), head_style))

    summary_rows = [
        [t("metric"),         t("value")],
        [t("total_value"),    f"{_fmt(total_value)} {rub}"],
        [t("total_cost"),     f"{_fmt(total_cost)} {rub}"],
        [t("pnl"),            f"{pnl_sign}{_fmt(total_profit)} {rub}"],
        [t("pnl_pct"),        f"{pnl_sign_pct}{pnl_pct:.2f}%"],
        [t("annual_coupon"),  f"{_fmt(annual_coupon)} {rub}"],
        [t("avg_ytm"),        f"{avg_ytm:.2f}%" if avg_ytm else t("na")],
        [t("count"),          str(len(rows))],
        [t("bonds_count"),    str(len(bonds))],
    ]

    pnl_color = C_GREEN if total_profit >= 0 else C_RED
    summ_table = Table(summary_rows, colWidths=[6.5 * cm, 5.5 * cm])
    summ_style = [
        ("BACKGROUND",    (0, 0), (-1, 0), C_DARK),
        ("TEXTCOLOR",     (0, 0), (-1, 0), colors.white),
        ("FONTNAME",      (0, 0), (-1, 0), font_bold),
        ("FONTNAME",      (0, 1), (-1, -1), font_name),
        ("FONTSIZE",      (0, 0), (-1, -1), 9),
        ("ROWBACKGROUNDS",(0, 1), (-1, -1), [colors.white, C_STRIPE]),
        ("GRID",          (0, 0), (-1, -1), 0.3, C_BORDER),
        ("PADDING",       (0, 0), (-1, -1), 5),
        ("ALIGN",         (1, 1), (1, -1), "RIGHT"),
        # Colour P&L row
        ("TEXTCOLOR",     (1, 3), (1, 4), pnl_color),
        ("FONTNAME",      (1, 3), (1, 4), font_bold),
    ]
    summ_table.setStyle(TableStyle(summ_style))
    elements.append(summ_table)
    elements.append(Spacer(1, 0.4 * cm))

    # ── Top-5 holdings ────────────────────────────────────────────────────
    if len(rows) >= 3:
        top5 = sorted(rows, key=lambda r: r.current_value or 0, reverse=True)[:5]
        elements.append(Paragraph(t("top_holdings"), head_style))
        top_data = [[t("col_ticker"), t("col_name"), t("col_value"), t("col_share"), t("col_rating")]]
        for r in top5:
            share = (r.current_value / total_value * 100) if total_value else 0
            top_data.append([
                str(r.ticker or ""),
                str(r.name or "")[:45],
                f"{_fmt(r.current_value or 0)} {rub}",
                f"{share:.1f}%",
                str(r.company_rating or t("na")),
            ])
        top_table = Table(top_data, colWidths=[2.5 * cm, 9 * cm, 4 * cm, 2.5 * cm, 2.5 * cm])
        top_table.setStyle(TableStyle([
            ("BACKGROUND",    (0, 0), (-1, 0), C_BLUE),
            ("TEXTCOLOR",     (0, 0), (-1, 0), colors.white),
            ("FONTNAME",      (0, 0), (-1, 0), font_bold),
            ("FONTNAME",      (0, 1), (-1, -1), font_name),
            ("FONTSIZE",      (0, 0), (-1, -1), 9),
            ("ROWBACKGROUNDS",(0, 1), (-1, -1), [colors.white, C_STRIPE]),
            ("GRID",          (0, 0), (-1, -1), 0.3, C_BORDER),
            ("PADDING",       (0, 0), (-1, -1), 5),
            ("ALIGN",         (2, 0), (3, -1), "RIGHT"),
            ("ALIGN",         (4, 0), (4, -1), "CENTER"),
        ]))
        elements.append(top_table)
        elements.append(Spacer(1, 0.4 * cm))

    # ── Main instruments table ────────────────────────────────────────────
    elements.append(Paragraph(t("instruments"), head_style))

    headers = [
        t("col_n"), t("col_ticker"), t("col_name"), t("col_type"),
        t("col_qty"), t("col_buy"), t("col_cur"), t("col_value"),
        t("col_pnl"), t("col_pnl_pct"), t("col_rating"),
        t("col_coupon_rate"), t("col_ytm"), t("col_maturity"), t("col_next_coupon"),
        t("col_weight"),
    ]

    # Landscape A4 usable width ≈ 28.1 cm (297mm − 2×0.8cm margin)
    # Total col widths: 27.1 cm — fits with ~1 cm spare
    col_w = [
        0.5, 1.8, 3.8, 1.5,   # №, тикер, название, тип
        1.2, 1.8, 1.8, 2.2,   # кол-во, цена покупки, тек. цена, стоимость
        1.8, 1.2, 1.5,         # P&L, P&L%, рейтинг
        1.5, 1.4, 1.8, 2.0,   # ставка купона, YTM, погашение, след.купон
        1.3,                   # доля
    ]
    col_w = [w * cm for w in col_w]

    # Wrap headers in Paragraph for word wrap support
    hdr_paragraphs = [Paragraph(h, header_cell_style) for h in headers]
    table_data = [hdr_paragraphs]
    total_pnl = 0.0

    def _cell(text: str) -> Paragraph:
        return Paragraph(str(text), cell_style)

    def _cell_r(text: str) -> Paragraph:
        return Paragraph(str(text), cell_style_r)

    for i, row in enumerate(rows, 1):
        pnl_val = ((row.current_price or 0) - (row.purchase_price or 0)) * (row.quantity or 0)
        total_pnl += pnl_val
        pnl_pct_row = ((row.current_price or 0) / (row.purchase_price or 1) - 1) * 100 if row.purchase_price else 0
        weight = (row.current_value / total_value * 100) if total_value else 0
        row_type = t("type_bond") if getattr(row, "type", "") == "bond" else t("type_stock")

        maturity = row.maturity_date.strftime("%m.%Y") if row.maturity_date else t("na")
        next_coup = row.next_coupon_date.strftime("%d.%m.%y") if row.next_coupon_date else t("na")
        ytm_str   = f"{row.market_yield:.1f}%" if getattr(row, "market_yield", None) else t("na")
        coupon_rate_str = f"{row.coupon_rate:.2f}%" if getattr(row, "coupon_rate", None) else t("na")
        rating_str = str(row.company_rating or t("na"))
        pnl_sign = "+" if pnl_val >= 0 else ""
        pct_sign = "+" if pnl_pct_row >= 0 else ""
        pnl_hex = "#16a34a" if pnl_val >= 0 else "#dc2626"

        # Name column uses word-wrap Paragraph; P&L cells use colour markup
        name_text = str(row.name or "")
        pnl_para = Paragraph(
            f'<font color="{pnl_hex}">{pnl_sign}{_fmt(pnl_val)}</font>',
            cell_style_r,
        )
        pct_para = Paragraph(
            f'<font color="{pnl_hex}">{pct_sign}{pnl_pct_row:.1f}%</font>',
            cell_style_r,
        )
        table_data.append([
            _cell(str(i)),
            _cell(str(row.ticker or "")),
            Paragraph(name_text, cell_style),   # word-wrap for long names
            _cell(row_type),
            _cell_r(str(int(row.quantity or 0))),
            _cell_r(_fmt2(row.purchase_price or 0)),
            _cell_r(_fmt2(row.current_price or 0)),
            _cell_r(_fmt(row.current_value or 0)),
            pnl_para,
            pct_para,
            _cell(rating_str),
            _cell_r(coupon_rate_str),
            _cell_r(ytm_str),
            _cell(maturity),
            _cell(next_coup),
            _cell_r(f"{weight:.1f}%"),
        ])

    # Total row
    total_pnl_pct = (total_pnl / total_cost * 100) if total_cost else 0
    total_style = ParagraphStyle("total_cell", fontName=font_bold, fontSize=7.5, leading=9, textColor=colors.white)
    total_style_r = ParagraphStyle("total_cell_r", fontName=font_bold, fontSize=7.5, leading=9, textColor=colors.white, alignment=2)
    tot_pnl_sign = "+" if total_pnl >= 0 else ""
    tot_pct_sign = "+" if total_pnl_pct >= 0 else ""
    table_data.append([
        Paragraph("", total_style),
        Paragraph(t("total_row"), total_style),
        Paragraph("", total_style),
        Paragraph("", total_style),
        Paragraph("", total_style),
        Paragraph("", total_style),
        Paragraph("", total_style),
        Paragraph(_fmt(total_value), total_style_r),
        Paragraph(f"{tot_pnl_sign}{_fmt(total_pnl)}", total_style_r),
        Paragraph(f"{tot_pct_sign}{total_pnl_pct:.1f}%", total_style_r),
        Paragraph("", total_style),
        Paragraph("", total_style),
        Paragraph("", total_style),
        Paragraph("", total_style),
        Paragraph("", total_style),
        Paragraph("100%", total_style_r),
    ])

    inst_table = Table(table_data, colWidths=col_w, repeatRows=1)

    last = len(table_data) - 1
    inst_style = [
        # Header — background only (text/align handled by Paragraph style)
        ("BACKGROUND",    (0, 0), (-1, 0), C_BLUE),
        ("VALIGN",        (0, 0), (-1, 0), "MIDDLE"),
        # Body
        ("ROWBACKGROUNDS",(0, 1), (-1, last - 1), [colors.white, C_STRIPE]),
        ("GRID",          (0, 0), (-1, last - 1), 0.3, C_BORDER),
        ("TOPPADDING",    (0, 0), (-1, -1), 2),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 2),
        ("LEFTPADDING",   (0, 0), (-1, -1), 2),
        ("RIGHTPADDING",  (0, 0), (-1, -1), 2),
        ("VALIGN",        (0, 1), (-1, -1), "MIDDLE"),
        # Total row — background only (text handled by Paragraph)
        ("BACKGROUND",    (0, last), (-1, last), C_DARK),
        ("LINEABOVE",     (0, last), (-1, last), 1, C_BLUE2),
    ]

    inst_table.setStyle(TableStyle(inst_style))
    elements.append(inst_table)

    # ── Disclaimer ────────────────────────────────────────────────────────
    elements.append(Spacer(1, 0.3 * cm))
    elements.append(Paragraph(t("disclaimer"), disc_style))

    doc.build(elements)
    return buf.getvalue()


# ── Fallback: fpdf2 ───────────────────────────────────────────────────────────

def _generate_pdf_fpdf(portfolio_name: str, rows, lang: str) -> bytes:
    """Fallback using fpdf2 (no Cyrillic support — ASCII only)."""
    from fpdf import FPDF

    t = lambda key: _t(lang, key)
    pdf = FPDF(orientation="L", unit="mm", format="A4")
    pdf.add_page()
    pdf.set_font("Helvetica", "B", size=16)
    pdf.cell(0, 10, t("title"), ln=True)
    pdf.set_font("Helvetica", size=11)
    pdf.cell(0, 8, f"{t('portfolio')}: {portfolio_name}", ln=True)
    pdf.cell(0, 8, f"{t('generated')}: {date.today().isoformat()}", ln=True)
    pdf.ln(5)

    total_value = sum(r.current_value or 0 for r in rows)
    total_cost  = sum((r.purchase_price or 0) * (r.quantity or 0) for r in rows)
    total_pnl   = total_value - total_cost

    pdf.set_font("Helvetica", "B", size=9)
    headers = [t("col_n"), t("col_ticker"), t("col_name"), t("col_qty"),
               t("col_buy"), t("col_cur"), t("col_value"), t("col_pnl"),
               t("col_rating"), t("col_ytm"), t("col_maturity")]
    widths  = [8, 18, 60, 12, 22, 22, 22, 22, 14, 14, 18]
    for h, w in zip(headers, widths):
        pdf.cell(w, 7, h[:12], border=1)
    pdf.ln()

    pdf.set_font("Helvetica", size=8)
    for i, row in enumerate(rows, 1):
        pnl = round(((row.current_price or 0) - (row.purchase_price or 0)) * (row.quantity or 0), 0)
        sign = "+" if pnl >= 0 else ""
        mat = row.maturity_date.strftime("%m/%Y") if row.maturity_date else "-"
        ytm = f"{row.market_yield:.1f}%" if getattr(row, "market_yield", None) else "-"
        vals = [
            str(i),
            str(row.ticker or ""),
            str(row.name or "")[:30],
            str(int(row.quantity or 0)),
            f"{row.purchase_price or 0:.2f}",
            f"{row.current_price or 0:.2f}",
            f"{row.current_value or 0:.0f}",
            f"{sign}{pnl:.0f}",
            str(row.company_rating or "-"),
            ytm,
            mat,
        ]
        for v, w in zip(vals, widths):
            pdf.cell(w, 6, str(v)[:14], border=1)
        pdf.ln()

    # Total row
    pdf.set_font("Helvetica", "B", size=8)
    pnl_s = "+" if total_pnl >= 0 else ""
    pdf.cell(sum(widths[:7]), 7, f"{t('total_row')}: {total_value:,.0f}  P&L: {pnl_s}{total_pnl:,.0f}", border=1)
    pdf.ln()

    return pdf.output()
